/* Level 2 - 성분으로 구분한 아이스크림 총 주문량 */
SELECT i.INGREDIENT_TYPE, SUM(f.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f
LEFT JOIN ICECREAM_INFO i ON (i.FLAVOR = f.FLAVOR)
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;

/* Level 3 - 즐겨찾기가 가장 많은 식당 정보 출력하기 */
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
    FROM REST_INFO
) AS REST_INFO
WHERE RN = 1
ORDER BY FOOD_TYPE DESC;
