/* Level 2 - 성분으로 구분한 아이스크림 총 주문량 */
SELECT i.INGREDIENT_TYPE, SUM(f.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f
LEFT JOIN ICECREAM_INFO i ON (i.FLAVOR = f.FLAVOR)
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;