/* Level 3 - 없어진 기록 찾기 */
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o
LEFT JOIN ANIMAL_INS i ON (o.ANIMAL_ID = i.ANIMAL_ID)
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID;

/* Level 3 - 있었는데요 없었습니다 */
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B ON(A.ANIMAL_ID = B.ANIMAL_ID)
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME ASC;

/* Level 3 - 오랜 기간 보호한 동물(1) */
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B ON (A.ANIMAL_ID = B.ANIMAL_ID)
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC
LIMIT 3;

/* Level 4 - 보호소에서 중성화한 동물 */
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME;