/* Level 1 - 상위 n개 레코드 */
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1;

/* Level 1 - 여러 기준으로 정렬하기 */
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

/* Level 1 - 동물의 아이디와 이름 */
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

/* Level 1 - 어린 동물 찾기 */
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID;

/* Level 1 - 아픈 동물 찾기 */
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;

/* Level 1 - 역순 정렬하기 */
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;